
name: Docker r Deplayment Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploay:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - run: docker build -t haseeb012/my-node-app:0.1 .
    - run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    - run: docker push haseeb012/my-node-app:0.1